name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Restore
      run: dotnet restore

    - name: Build CLI
      run: dotnet build -c Release ./Decompiler/Decompiler.csproj

    - name: Build Library
      run: dotnet build -c Release ./ValveResourceFormat/ValveResourceFormat.csproj

    - name: Run tests
      run: dotnet test ./Tests/Tests.csproj

    - name: Upload CLI artifact
      uses: actions/upload-artifact@v1
      with:
        name: CLI
        path: Decompiler/bin/Release

    - name: Upload GUI artifact
      uses: actions/upload-artifact@v1
      with:
        name: GUI
        path: GUI/bin/Release
